version: '3'

services:
  laravel:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel-api
    working_dir: /var/www/html
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./backend/projeto/cepinfo:/var/www/html
    command:
      # Ao iniciar o container vai verificar se o container do banco ja está funcionando e caso sim, faz o migrate e inicia o server laravel.
      - sh
      - -c
      - |
        dockerize -wait tcp://172.16.0.4:5432
        php artisan migrate
        php artisan serve --host=0.0.0.0 --port=8000
    networks:
      desafio_network:
        ipv4_address: 172.16.0.2
  
  vue:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue-app
    working_dir: /app/cepinfo-app/cepinfo-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./frontend/projeto:/app
    command: ["npm", "run", "serve"]
    networks:
      desafio_network:
        ipv4_address: 172.16.0.3

  postgres:
    build:
      context: ./banco
      dockerfile: Dockerfile
    container_name: banco-postgres
    ports:
      - "5432:5432"
    networks:
      desafio_network:
        ipv4_address: 172.16.0.4


networks:
  desafio_network:
    external: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24

